#!/usr/bin/env bash

# get bash colors and styles here:
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        echo -e "${C_GREEN}OK!${C_RESET}"
    else
        echo -e "${C_RED}NOK!${C_RESET}\n\n$output"
        exit 1
    fi
}

modified="git diff --diff-filter=M --name-only --cached  | grep \".php$\""

__run "1/8" "php lint" "${modified} | xargs -r php -l"
__run "2/8" "phpstan" "vendor/bin/phpstan"
__run "3/8" "psalm" "vendor/bin/psalm"
__run "4/8" "php-cs-fixer" "vendor/bin/php-cs-fixer fix --dry-run --allow-risky=yes"
__run "5/8" "yaml lint" "bin/console lint:yaml"
__run "6/8" "container lint" "bin/console lint:container"
__run "7/8" "twig lint" "bin/console lint:twig templates"
__run "8/8" "rector check" "vendor/bin/rector process -n"
